"""Generate the per-tool shims from `.claude/skills/` so the kit loads everywhere.

The skills are the source of truth. Every other file this writes is derived, carries a
"generated" banner, and is safe to delete and rebuild:

    .cursor/commands/<name>.md   Cursor slash commands
    AGENTS.md                    read by Cursor, Antigravity, Codex, Copilot and others

Writing each tool's format by hand is how the copies drift: someone fixes a rule in the
Cursor version, nobody ports it back, and two agents start giving different answers about
the same repository. One source, regenerated, cannot drift.

    python3 tools/sync_agent_files.py            # write
    python3 tools/sync_agent_files.py --check    # fail if anything is stale (for CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

BANNER = "<!-- Generated by tools/sync_agent_files.py from .claude/skills/. Do not edit. -->"

_FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    body: str
    path: Path

    @property
    def summary(self) -> str:
        """The first sentence of the description — enough for an index row."""
        head = self.description.split(". ")[0].strip()
        return head.rstrip(".") + "." if head else ""


def read_skill(skill_md: Path) -> Skill:
    text = skill_md.read_text(encoding="utf-8")
    match = _FRONTMATTER.match(text)
    if not match:
        raise ValueError(f"{skill_md} has no YAML frontmatter")

    fields: dict[str, str] = {}
    key = None
    for line in match.group(1).splitlines():
        if re.match(r"^[a-zA-Z_-]+:", line):
            key, _, value = line.partition(":")
            key = key.strip()
            fields[key] = value.strip()
        elif key and line.startswith((" ", "\t")):
            # A folded continuation line; descriptions routinely wrap.
            fields[key] = (fields[key] + " " + line.strip()).strip()

    name = fields.get("name") or skill_md.parent.name
    return Skill(
        name=name,
        description=fields.get("description", ""),
        body=text[match.end() :].strip(),
        path=skill_md,
    )


def discover(root: Path) -> list[Skill]:
    skills = [
        read_skill(path) for path in sorted(root.glob(".claude/skills/*/SKILL.md"))
    ]
    if not skills:
        raise SystemExit(f"no skills found under {root / '.claude/skills'}")
    return skills


def render_cursor_command(skill: Skill, root: Path) -> str:
    """A Cursor command is plain markdown; the filename becomes the `/name`."""
    references = sorted((skill.path.parent / "references").glob("*.md"))
    scripts = sorted((skill.path.parent / "scripts").glob("*"))
    templates = sorted((skill.path.parent / "templates").glob("*"))

    lines = [BANNER, "", f"# /{skill.name}", "", skill.description, "", "---", "", skill.body]

    extra: list[str] = []
    for label, paths in (
        ("Schemas and references", references),
        ("Scripts", scripts),
        ("Templates", templates),
    ):
        if not paths:
            continue
        extra.append(f"### {label}")
        extra.append("")
        for path in paths:
            extra.append(f"- `{path.relative_to(root)}`")
        extra.append("")

    if extra:
        lines += ["", "## Supporting files", "", "Read these when the body refers to them.", "", *extra]

    return "\n".join(lines).rstrip() + "\n"


def render_agents_md(skills: list[Skill], root: Path) -> str:
    rows = "\n".join(
        f"| `{skill.name}` | {skill.summary} |" for skill in skills
    )
    has_orchestrator = (root / "orchestrator").is_dir()

    sections = [
        BANNER,
        "",
        "# AGENTS.md",
        "",
        "Spec-driven development kit. Work moves through a fixed chain of artifacts, and "
        "every stage reads the one before it rather than re-deriving intent from the "
        "original request.",
        "",
        "## The chain",
        "",
        "```",
        "requirements.md  ->  design.md  ->  tasks.json  ->  [human gate]  ->  dev agents",
        "```",
        "",
        "Artifacts live in `docs/features/<slug>/`. Repository context lives in "
        "`.agentteam/repo-map.md` and `.agentteam/company.md`.",
        "",
        "## Skills",
        "",
        "| Skill | Purpose |",
        "|---|---|",
        rows,
        "",
        "Each skill's full instructions are in `.claude/skills/<name>/SKILL.md`, mirrored "
        "as Cursor commands in `.cursor/commands/`.",
        "",
        "## House rules",
        "",
        "- **Never widen a task past its `owns` globs.** Tasks run concurrently in "
        "separate worktrees; files outside your globs belong to another agent and your "
        "edits to them will be discarded at merge time.",
        "- **Tests are the exit condition**, not your own judgement that the code looks "
        "right. A bug is filed as a failing test, never as prose.",
        "- **Open questions are batched.** Add them to the numbered `Qn` list in the "
        "current artifact rather than asking one at a time.",
        "- **Never put credentials, connection strings or customer data** in "
        "`.agentteam/` files — they are committed and read straight into prompts.",
    ]

    if has_orchestrator:
        sections += [
            "",
            "## Commands",
            "",
            "```console",
            "python3 -m orchestrator validate docs/features/<slug>/tasks.json",
            "python3 -m orchestrator schedule docs/features/<slug>/tasks.json",
            "python3 -m orchestrator run      docs/features/<slug>/tasks.json",
            "python3 -m unittest discover -s tests",
            "```",
        ]

    return "\n".join(sections).rstrip() + "\n"


def plan_outputs(root: Path) -> dict[Path, str]:
    skills = discover(root)
    outputs: dict[Path, str] = {
        root / ".cursor" / "commands" / f"{skill.name}.md": render_cursor_command(
            skill, root
        )
        for skill in skills
    }
    outputs[root / "AGENTS.md"] = render_agents_md(skills, root)
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root", default=".", help="repository root (default: current directory)"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated file is missing or stale, writing nothing",
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    outputs = plan_outputs(root)
    stale: list[Path] = []

    for path, content in sorted(outputs.items()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("stale generated files (run tools/sync_agent_files.py):", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(root)}", file=sys.stderr)
            return 1
        print(f"{len(outputs)} generated file(s) up to date")
        return 0

    if stale:
        for path in stale:
            print(f"wrote {path.relative_to(root)}")
    else:
        print(f"{len(outputs)} generated file(s) already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
